<?php

    $method = $_SERVER['REQUEST_METHOD'];
    header('Content-Type: application/json');
    if ($method === 'POST') {
        $token = isset($_POST['token']) ? $_POST['token'] : false;
        $url = 'http://localhost:3000/api/whatsapp/create-instance';
        if ( $token ) {

            $data = [
                'token' => $token
            ];
            $payload = json_encode($data);

            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);

            $headers = array();
            $headers[] = 'Content-Type: application/json';
            $headers[] = 'Authorization: Basic TmRhbHUtc2VydmVyLXVVZGtmZ2xpNzgzcGtmbmxhc2tvZ29pZ2hyOg==';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);

            echo $result;
            // echo json_encode($data);

        } else {
            echo json_encode(['status' => false, 'message' => 'Check Input']);
        }
    } else {
        echo json_encode(['status' => false]);
    }
    
?>